In [1]:
import pandas as pd
import numpy as np

In [2]:
from scipy import stats

In [3]:
pitch = pd.read_csv('pitchwin.csv')
pitch

Ground  Cskplayed  Cskwon    Win%   Lose%
0          Chennai         56      40   71.43   28.57
1           Mumbai         25      15   60.00   40.00
2            Dubai         14       9   64.29   35.71
3          Kolkata         11       5   45.45   54.55
4            Delhi         10       7   70.00   30.00
5        Bengaluru          9       5   55.56   44.44
6             Pune          8       6   75.00   25.00
7        Abu Dhabi          8       4   50.00   50.00
8          Sharjah          6       3   50.00   50.00
9           Mohali          6       3   50.00   50.00
10          Jaipur          6       3   50.00   50.00
11       Hyderabad          6       3   50.00   50.00
12          Ranchi          5       3   60.00   40.00
13          Durban          4       1   25.00   75.00
14   Visakhapatnam          2       2  100.00    0.00
15  Port Elizabeth          2       2  100.00    0.00
16    Johannesburg          2       1   50.00   50.00
17     East London          2       2  100.00    0.00
18      Dharamsala          2       1   50.00   50.00
19       Centurion          2       1   50.00   50.00
20       Ahmedabad          2       0    0.00  100.00
21          Raipur          1       0    0.00  100.00
22          Nagpur          1       0    0.00  100.00
23           Kochi          1       0    0.00  100.00
24       Kimberley          1       1  100.00    0.00
25         Cuttack          1       0    0.00  100.00
26       Cape Town          1       0    0.00  100.00

In [4]:
days = pd.read_csv('MatchDay.csv')
days

Day  Cskplayed  Cskwon   Win%  Lose%
0   Saturday         41      25  60.98  39.02
1     Sunday         38      20  52.63  47.37
2  Wednesday         24      16  66.67  33.33
3    Tuesday         24      16  66.67  33.33
4   Thursday         24      15  62.50  37.50
5     Friday         24      13  54.17  45.83
6     Monday         19      12  63.16  36.84

In [5]:
teams = pd.read_csv('OppTeam.csv')
teams

Opponent  CSKLost  CSKWon  CSKPlayed   Win%  Lose%
0               Mumbai Indians       19      13         32  40.62  59.38
1             Rajasthan Royals       10      15         25  60.00  40.00
2                 Punjab Kings       10      15         25  60.00  40.00
3               Delhi Capitals       10      16         26  61.54  38.46
4  Royal Challengers Bangalore        9      18         27  66.67  33.33
5          Sunrisers Hyderabad        8      18         26  69.23  30.77
6        Kolkata Knight Riders        8      17         25  68.00  32.00
7                Pune Warriors        2       4          6  66.67  33.33
8         Kochi Tuskers Kerala        1       1          2  50.00  50.00

### Significance Test for Pitch vs Win/Lose

In [8]:
grnd = pd.pivot_table(pitch, index = ['Ground'], values = ['Win%', 'Lose%'])

In [9]:
from scipy.stats import chi2_contingency
chi2, p, dof, tbl = chi2_contingency(grnd)

In [10]:
chi2

1102.1278515042427

In [11]:
p

7.936125606223482e-216

In [12]:
dof

26

In [13]:
tbl

array([[50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815],
       [50.86185185, 49.13814815]])

In [14]:
stats.chi2.ppf(0.99,26)

45.64168266628317

In [15]:
stats.chi2.ppf(0.95,26)

38.885138659830055

### Significance Test for Pitch with min 4 matches played vs Win/Lose

In [35]:
grnd1 = pd.pivot_table(pitch[:13], index = ['Ground'], values = ['Win%', 'Lose%'])

In [39]:
chi2, p, dof, tbl = chi2_contingency(grnd1)

In [40]:
chi2

46.908557996824555

In [41]:
dof

12

In [42]:
stats.chi2.ppf(0.99,12)

26.216967305535853

In [43]:
stats.chi2.ppf(0.95,12)

21.02606981748307

### Significance Test for Match Days vs Win/Lose

In [17]:
Days = pd.pivot_table(days, index = ['Day'], values = ['Win%', 'Lose%'])

In [18]:
chi2, p, dof, tbl = chi2_contingency(Days)

In [19]:
chi2

7.8965180718978

In [20]:
p

0.24578313991072456

In [21]:
dof

6

In [22]:
tbl

array([[39.03142857, 60.96857143],
       [39.03142857, 60.96857143],
       [39.03142857, 60.96857143],
       [39.03142857, 60.96857143],
       [39.03142857, 60.96857143],
       [39.03142857, 60.96857143],
       [39.03142857, 60.96857143]])

In [23]:
stats.chi2.ppf(0.95,6)

12.591587243743977

In [24]:
stats.chi2.ppf(0.99,6)

16.811893829770927

### Significance Test for Teams vs Win/Lose

In [25]:
Opp = pd.pivot_table(teams, index = ['Opponent'], values = ['Win%', 'Lose%'])

In [26]:
chi2, p, dof, tbl = chi2_contingency(Opp)

In [27]:
chi2   # Calculated Chi2

29.880785888347127

In [28]:
p

0.00022188348869309768

In [31]:
dof

8

In [32]:
# Expected Frequencies
tbl

array([[39.69666667, 60.30333333],
       [39.69666667, 60.30333333],
       [39.69666667, 60.30333333],
       [39.69666667, 60.30333333],
       [39.69666667, 60.30333333],
       [39.69666667, 60.30333333],
       [39.69666667, 60.30333333],
       [39.69666667, 60.30333333],
       [39.69666667, 60.30333333]])

In [33]:
stats.chi2.ppf(0.95,8)   # Chi2 for 5% level of significance, dof = 8

15.50731305586545

In [34]:
stats.chi2.ppf(0.99,8)   # Chi2 for 1% level of significance, dof =  8 

20.090235029663233